/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuoteId = IDL.Nat;
export const QuoteStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'replied' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const EstimationBreakdown = IDL.Record({
  'hours' : IDL.Nat,
  'hourlyRate' : IDL.Nat,
  'labor' : IDL.Nat,
  'notes' : IDL.Text,
  'materials' : IDL.Nat,
});
export const ServiceId = IDL.Nat;
export const ReplyType = IDL.Variant({
  'detailedEstimate' : IDL.Null,
  'onSiteEstimate' : IDL.Null,
  'messageOnly' : IDL.Null,
});
export const QuoteView = IDL.Record({
  'id' : QuoteId,
  'status' : QuoteStatus,
  'clientId' : UserId,
  'createdAt' : Timestamp,
  'estimationBreakdown' : IDL.Opt(EstimationBreakdown),
  'updatedAt' : Timestamp,
  'replyMessage' : IDL.Opt(IDL.Text),
  'proposedPrice' : IDL.Opt(IDL.Nat),
  'serviceId' : ServiceId,
  'replyType' : IDL.Opt(ReplyType),
  'requirements' : IDL.Text,
  'providerId' : UserId,
  'attachments' : IDL.Vec(IDL.Text),
  'proposedTimeline' : IDL.Opt(IDL.Text),
});
export const BookingId = IDL.Nat;
export const EscrowStatus = IDL.Variant({
  'held' : IDL.Null,
  'none' : IDL.Null,
  'refunded' : IDL.Null,
  'released' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'disputed' : IDL.Null,
  'started' : IDL.Null,
  'completed' : IDL.Null,
  'paymentPending' : IDL.Null,
});
export const BookingView = IDL.Record({
  'id' : BookingId,
  'clientId' : UserId,
  'createdAt' : Timestamp,
  'quoteId' : QuoteId,
  'agreedPrice' : IDL.Nat,
  'escrowStatus' : EscrowStatus,
  'updatedAt' : Timestamp,
  'bookingStatus' : BookingStatus,
  'serviceId' : ServiceId,
  'providerId' : UserId,
});
export const CreateRatingInput = IDL.Record({
  'bookingId' : BookingId,
  'comment' : IDL.Opt(IDL.Text),
  'stars' : IDL.Nat,
});
export const RatingId = IDL.Nat;
export const RatingView = IDL.Record({
  'id' : RatingId,
  'clientId' : UserId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'comment' : IDL.Opt(IDL.Text),
  'stars' : IDL.Nat,
  'providerReply' : IDL.Opt(IDL.Text),
  'serviceId' : ServiceId,
  'providerId' : UserId,
});
export const ServiceCategory = IDL.Variant({
  'it' : IDL.Null,
  'cleaning' : IDL.Null,
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'garden' : IDL.Null,
  'design' : IDL.Null,
  'homeRepair' : IDL.Null,
});
export const PriceType = IDL.Variant({
  'fixed' : IDL.Null,
  'onSiteEstimate' : IDL.Null,
});
export const CreateServiceInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'priceType' : PriceType,
  'basePrice' : IDL.Nat,
});
export const ServiceView = IDL.Record({
  'id' : ServiceId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : ServiceCategory,
  'priceType' : PriceType,
  'basePrice' : IDL.Nat,
  'providerId' : UserId,
});
export const InvoiceId = IDL.Nat;
export const InvoiceView = IDL.Record({
  'id' : InvoiceId,
  'clientId' : UserId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'serviceId' : ServiceId,
  'amount' : IDL.Nat,
  'providerId' : UserId,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'provider' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'bookingConfirmed' : IDL.Null,
  'paymentReceived' : IDL.Null,
  'quoteReceived' : IDL.Null,
  'replyReceived' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'body' : IDL.Text,
  'link' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'recipientId' : UserId,
});
export const RegisterInput = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : UserRole,
});
export const ReplyQuoteInput = IDL.Record({
  'estimationBreakdown' : IDL.Opt(EstimationBreakdown),
  'replyMessage' : IDL.Opt(IDL.Text),
  'proposedPrice' : IDL.Opt(IDL.Nat),
  'replyType' : ReplyType,
  'proposedTimeline' : IDL.Opt(IDL.Text),
});
export const RequestQuoteInput = IDL.Record({
  'serviceId' : ServiceId,
  'requirements' : IDL.Text,
  'attachments' : IDL.Vec(IDL.Text),
});
export const UpdateServiceInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ServiceCategory),
  'priceType' : IDL.Opt(PriceType),
  'basePrice' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'acceptQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
  'cancelBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
  'cancelQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
  'createBooking' : IDL.Func([QuoteId], [BookingView], []),
  'createRating' : IDL.Func([CreateRatingInput], [RatingView], []),
  'createService' : IDL.Func([CreateServiceInput], [ServiceView], []),
  'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
  'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceView)], []),
  'getInvoiceByBooking' : IDL.Func([BookingId], [IDL.Opt(InvoiceView)], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(ServiceView)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'listMyClientBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'listMyClientInvoices' : IDL.Func([], [IDL.Vec(InvoiceView)], ['query']),
  'listMyClientQuotes' : IDL.Func([], [IDL.Vec(QuoteView)], ['query']),
  'listMyProviderBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'listMyProviderInvoices' : IDL.Func([], [IDL.Vec(InvoiceView)], ['query']),
  'listMyProviderQuotes' : IDL.Func([], [IDL.Vec(QuoteView)], ['query']),
  'listMyServices' : IDL.Func([], [IDL.Vec(ServiceView)], ['query']),
  'listNotifications' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(NotificationView)],
      ['query'],
    ),
  'listProviderRatings' : IDL.Func([UserId], [IDL.Vec(RatingView)], ['query']),
  'listServiceRatings' : IDL.Func(
      [ServiceId],
      [IDL.Vec(RatingView)],
      ['query'],
    ),
  'listServices' : IDL.Func(
      [IDL.Opt(ServiceCategory)],
      [IDL.Vec(ServiceView)],
      ['query'],
    ),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markBookingCompleted' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
  'markBookingDisputed' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
  'markBookingStarted' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
  'markNotificationAsRead' : IDL.Func(
      [NotificationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func([RegisterInput], [UserProfile], []),
  'rejectQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
  'releaseEscrow' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
  'replyQuote' : IDL.Func([QuoteId, ReplyQuoteInput], [IDL.Opt(QuoteView)], []),
  'replyRating' : IDL.Func([RatingId, IDL.Text], [IDL.Opt(RatingView)], []),
  'requestQuote' : IDL.Func([RequestQuoteInput], [QuoteView], []),
  'updateService' : IDL.Func(
      [ServiceId, UpdateServiceInput],
      [IDL.Opt(ServiceView)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuoteId = IDL.Nat;
  const QuoteStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'replied' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const EstimationBreakdown = IDL.Record({
    'hours' : IDL.Nat,
    'hourlyRate' : IDL.Nat,
    'labor' : IDL.Nat,
    'notes' : IDL.Text,
    'materials' : IDL.Nat,
  });
  const ServiceId = IDL.Nat;
  const ReplyType = IDL.Variant({
    'detailedEstimate' : IDL.Null,
    'onSiteEstimate' : IDL.Null,
    'messageOnly' : IDL.Null,
  });
  const QuoteView = IDL.Record({
    'id' : QuoteId,
    'status' : QuoteStatus,
    'clientId' : UserId,
    'createdAt' : Timestamp,
    'estimationBreakdown' : IDL.Opt(EstimationBreakdown),
    'updatedAt' : Timestamp,
    'replyMessage' : IDL.Opt(IDL.Text),
    'proposedPrice' : IDL.Opt(IDL.Nat),
    'serviceId' : ServiceId,
    'replyType' : IDL.Opt(ReplyType),
    'requirements' : IDL.Text,
    'providerId' : UserId,
    'attachments' : IDL.Vec(IDL.Text),
    'proposedTimeline' : IDL.Opt(IDL.Text),
  });
  const BookingId = IDL.Nat;
  const EscrowStatus = IDL.Variant({
    'held' : IDL.Null,
    'none' : IDL.Null,
    'refunded' : IDL.Null,
    'released' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'started' : IDL.Null,
    'completed' : IDL.Null,
    'paymentPending' : IDL.Null,
  });
  const BookingView = IDL.Record({
    'id' : BookingId,
    'clientId' : UserId,
    'createdAt' : Timestamp,
    'quoteId' : QuoteId,
    'agreedPrice' : IDL.Nat,
    'escrowStatus' : EscrowStatus,
    'updatedAt' : Timestamp,
    'bookingStatus' : BookingStatus,
    'serviceId' : ServiceId,
    'providerId' : UserId,
  });
  const CreateRatingInput = IDL.Record({
    'bookingId' : BookingId,
    'comment' : IDL.Opt(IDL.Text),
    'stars' : IDL.Nat,
  });
  const RatingId = IDL.Nat;
  const RatingView = IDL.Record({
    'id' : RatingId,
    'clientId' : UserId,
    'bookingId' : BookingId,
    'createdAt' : Timestamp,
    'comment' : IDL.Opt(IDL.Text),
    'stars' : IDL.Nat,
    'providerReply' : IDL.Opt(IDL.Text),
    'serviceId' : ServiceId,
    'providerId' : UserId,
  });
  const ServiceCategory = IDL.Variant({
    'it' : IDL.Null,
    'cleaning' : IDL.Null,
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'garden' : IDL.Null,
    'design' : IDL.Null,
    'homeRepair' : IDL.Null,
  });
  const PriceType = IDL.Variant({
    'fixed' : IDL.Null,
    'onSiteEstimate' : IDL.Null,
  });
  const CreateServiceInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'priceType' : PriceType,
    'basePrice' : IDL.Nat,
  });
  const ServiceView = IDL.Record({
    'id' : ServiceId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : ServiceCategory,
    'priceType' : PriceType,
    'basePrice' : IDL.Nat,
    'providerId' : UserId,
  });
  const InvoiceId = IDL.Nat;
  const InvoiceView = IDL.Record({
    'id' : InvoiceId,
    'clientId' : UserId,
    'bookingId' : BookingId,
    'createdAt' : Timestamp,
    'serviceId' : ServiceId,
    'amount' : IDL.Nat,
    'providerId' : UserId,
  });
  const UserRole = IDL.Variant({ 'client' : IDL.Null, 'provider' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'bookingConfirmed' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'quoteReceived' : IDL.Null,
    'replyReceived' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'body' : IDL.Text,
    'link' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'recipientId' : UserId,
  });
  const RegisterInput = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : UserRole,
  });
  const ReplyQuoteInput = IDL.Record({
    'estimationBreakdown' : IDL.Opt(EstimationBreakdown),
    'replyMessage' : IDL.Opt(IDL.Text),
    'proposedPrice' : IDL.Opt(IDL.Nat),
    'replyType' : ReplyType,
    'proposedTimeline' : IDL.Opt(IDL.Text),
  });
  const RequestQuoteInput = IDL.Record({
    'serviceId' : ServiceId,
    'requirements' : IDL.Text,
    'attachments' : IDL.Vec(IDL.Text),
  });
  const UpdateServiceInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ServiceCategory),
    'priceType' : IDL.Opt(PriceType),
    'basePrice' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'acceptQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
    'cancelBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
    'cancelQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
    'createBooking' : IDL.Func([QuoteId], [BookingView], []),
    'createRating' : IDL.Func([CreateRatingInput], [RatingView], []),
    'createService' : IDL.Func([CreateServiceInput], [ServiceView], []),
    'deleteService' : IDL.Func([ServiceId], [IDL.Bool], []),
    'getBooking' : IDL.Func([BookingId], [IDL.Opt(BookingView)], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceView)], []),
    'getInvoiceByBooking' : IDL.Func([BookingId], [IDL.Opt(InvoiceView)], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(ServiceView)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'listMyClientBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'listMyClientInvoices' : IDL.Func([], [IDL.Vec(InvoiceView)], ['query']),
    'listMyClientQuotes' : IDL.Func([], [IDL.Vec(QuoteView)], ['query']),
    'listMyProviderBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'listMyProviderInvoices' : IDL.Func([], [IDL.Vec(InvoiceView)], ['query']),
    'listMyProviderQuotes' : IDL.Func([], [IDL.Vec(QuoteView)], ['query']),
    'listMyServices' : IDL.Func([], [IDL.Vec(ServiceView)], ['query']),
    'listNotifications' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(NotificationView)],
        ['query'],
      ),
    'listProviderRatings' : IDL.Func(
        [UserId],
        [IDL.Vec(RatingView)],
        ['query'],
      ),
    'listServiceRatings' : IDL.Func(
        [ServiceId],
        [IDL.Vec(RatingView)],
        ['query'],
      ),
    'listServices' : IDL.Func(
        [IDL.Opt(ServiceCategory)],
        [IDL.Vec(ServiceView)],
        ['query'],
      ),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markBookingCompleted' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
    'markBookingDisputed' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
    'markBookingStarted' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
    'markNotificationAsRead' : IDL.Func(
        [NotificationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func([RegisterInput], [UserProfile], []),
    'rejectQuote' : IDL.Func([QuoteId], [IDL.Opt(QuoteView)], []),
    'releaseEscrow' : IDL.Func([BookingId], [IDL.Opt(BookingView)], []),
    'replyQuote' : IDL.Func(
        [QuoteId, ReplyQuoteInput],
        [IDL.Opt(QuoteView)],
        [],
      ),
    'replyRating' : IDL.Func([RatingId, IDL.Text], [IDL.Opt(RatingView)], []),
    'requestQuote' : IDL.Func([RequestQuoteInput], [QuoteView], []),
    'updateService' : IDL.Func(
        [ServiceId, UpdateServiceInput],
        [IDL.Opt(ServiceView)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };