/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'disputed' : null } |
  { 'started' : null } |
  { 'completed' : null } |
  { 'paymentPending' : null };
export interface BookingView {
  'id' : BookingId,
  'clientId' : UserId,
  'createdAt' : Timestamp,
  'quoteId' : QuoteId,
  'agreedPrice' : bigint,
  'escrowStatus' : EscrowStatus,
  'updatedAt' : Timestamp,
  'bookingStatus' : BookingStatus,
  'serviceId' : ServiceId,
  'providerId' : UserId,
}
export interface CreateRatingInput {
  'bookingId' : BookingId,
  'comment' : [] | [string],
  'stars' : bigint,
}
export interface CreateServiceInput {
  'title' : string,
  'description' : string,
  'category' : ServiceCategory,
  'priceType' : PriceType,
  'basePrice' : bigint,
}
export type EscrowStatus = { 'held' : null } |
  { 'none' : null } |
  { 'refunded' : null } |
  { 'released' : null };
export interface EstimationBreakdown {
  'hours' : bigint,
  'hourlyRate' : bigint,
  'labor' : bigint,
  'notes' : string,
  'materials' : bigint,
}
export type InvoiceId = bigint;
export interface InvoiceView {
  'id' : InvoiceId,
  'clientId' : UserId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'serviceId' : ServiceId,
  'amount' : bigint,
  'providerId' : UserId,
}
export type NotificationId = bigint;
export type NotificationType = { 'bookingConfirmed' : null } |
  { 'paymentReceived' : null } |
  { 'quoteReceived' : null } |
  { 'replyReceived' : null };
export interface NotificationView {
  'id' : NotificationId,
  'title' : string,
  'notifType' : NotificationType,
  'body' : string,
  'link' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'recipientId' : UserId,
}
export type PriceType = { 'fixed' : null } |
  { 'onSiteEstimate' : null };
export type QuoteId = bigint;
export type QuoteStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'replied' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface QuoteView {
  'id' : QuoteId,
  'status' : QuoteStatus,
  'clientId' : UserId,
  'createdAt' : Timestamp,
  'estimationBreakdown' : [] | [EstimationBreakdown],
  'updatedAt' : Timestamp,
  'replyMessage' : [] | [string],
  'proposedPrice' : [] | [bigint],
  'serviceId' : ServiceId,
  'replyType' : [] | [ReplyType],
  'requirements' : string,
  'providerId' : UserId,
  'attachments' : Array<string>,
  'proposedTimeline' : [] | [string],
}
export type RatingId = bigint;
export interface RatingView {
  'id' : RatingId,
  'clientId' : UserId,
  'bookingId' : BookingId,
  'createdAt' : Timestamp,
  'comment' : [] | [string],
  'stars' : bigint,
  'providerReply' : [] | [string],
  'serviceId' : ServiceId,
  'providerId' : UserId,
}
export interface RegisterInput {
  'bio' : string,
  'displayName' : string,
  'role' : UserRole,
}
export interface ReplyQuoteInput {
  'estimationBreakdown' : [] | [EstimationBreakdown],
  'replyMessage' : [] | [string],
  'proposedPrice' : [] | [bigint],
  'replyType' : ReplyType,
  'proposedTimeline' : [] | [string],
}
export type ReplyType = { 'detailedEstimate' : null } |
  { 'onSiteEstimate' : null } |
  { 'messageOnly' : null };
export interface RequestQuoteInput {
  'serviceId' : ServiceId,
  'requirements' : string,
  'attachments' : Array<string>,
}
export type ServiceCategory = { 'it' : null } |
  { 'cleaning' : null } |
  { 'other' : null } |
  { 'marketing' : null } |
  { 'garden' : null } |
  { 'design' : null } |
  { 'homeRepair' : null };
export type ServiceId = bigint;
export interface ServiceView {
  'id' : ServiceId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : ServiceCategory,
  'priceType' : PriceType,
  'basePrice' : bigint,
  'providerId' : UserId,
}
export type Timestamp = bigint;
export interface UpdateServiceInput {
  'title' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [ServiceCategory],
  'priceType' : [] | [PriceType],
  'basePrice' : [] | [bigint],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type UserRole = { 'client' : null } |
  { 'provider' : null };
export interface _SERVICE {
  'acceptQuote' : ActorMethod<[QuoteId], [] | [QuoteView]>,
  'cancelBooking' : ActorMethod<[BookingId], [] | [BookingView]>,
  'cancelQuote' : ActorMethod<[QuoteId], [] | [QuoteView]>,
  'createBooking' : ActorMethod<[QuoteId], BookingView>,
  'createRating' : ActorMethod<[CreateRatingInput], RatingView>,
  'createService' : ActorMethod<[CreateServiceInput], ServiceView>,
  'deleteService' : ActorMethod<[ServiceId], boolean>,
  'getBooking' : ActorMethod<[BookingId], [] | [BookingView]>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [InvoiceView]>,
  'getInvoiceByBooking' : ActorMethod<[BookingId], [] | [InvoiceView]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getQuote' : ActorMethod<[QuoteId], [] | [QuoteView]>,
  'getService' : ActorMethod<[ServiceId], [] | [ServiceView]>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'listMyClientBookings' : ActorMethod<[], Array<BookingView>>,
  'listMyClientInvoices' : ActorMethod<[], Array<InvoiceView>>,
  'listMyClientQuotes' : ActorMethod<[], Array<QuoteView>>,
  'listMyProviderBookings' : ActorMethod<[], Array<BookingView>>,
  'listMyProviderInvoices' : ActorMethod<[], Array<InvoiceView>>,
  'listMyProviderQuotes' : ActorMethod<[], Array<QuoteView>>,
  'listMyServices' : ActorMethod<[], Array<ServiceView>>,
  'listNotifications' : ActorMethod<[bigint, bigint], Array<NotificationView>>,
  'listProviderRatings' : ActorMethod<[UserId], Array<RatingView>>,
  'listServiceRatings' : ActorMethod<[ServiceId], Array<RatingView>>,
  'listServices' : ActorMethod<[[] | [ServiceCategory]], Array<ServiceView>>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markBookingCompleted' : ActorMethod<[BookingId], [] | [BookingView]>,
  'markBookingDisputed' : ActorMethod<[BookingId], [] | [BookingView]>,
  'markBookingStarted' : ActorMethod<[BookingId], [] | [BookingView]>,
  'markNotificationAsRead' : ActorMethod<
    [NotificationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<[RegisterInput], UserProfile>,
  'rejectQuote' : ActorMethod<[QuoteId], [] | [QuoteView]>,
  'releaseEscrow' : ActorMethod<[BookingId], [] | [BookingView]>,
  'replyQuote' : ActorMethod<[QuoteId, ReplyQuoteInput], [] | [QuoteView]>,
  'replyRating' : ActorMethod<[RatingId, string], [] | [RatingView]>,
  'requestQuote' : ActorMethod<[RequestQuoteInput], QuoteView>,
  'updateService' : ActorMethod<
    [ServiceId, UpdateServiceInput],
    [] | [ServiceView]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];