/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateServiceInput {
    title?: string;
    description?: string;
    category?: ServiceCategory;
    priceType?: PriceType;
    basePrice?: bigint;
}
export type Timestamp = bigint;
export interface RequestQuoteInput {
    serviceId: ServiceId;
    requirements: string;
    attachments: Array<string>;
}
export interface NotificationView {
    id: NotificationId;
    title: string;
    notifType: NotificationType;
    body: string;
    link: string;
    createdAt: Timestamp;
    isRead: boolean;
    recipientId: UserId;
}
export type QuoteId = bigint;
export interface EstimationBreakdown {
    hours: bigint;
    hourlyRate: bigint;
    labor: bigint;
    notes: string;
    materials: bigint;
}
export interface RegisterInput {
    bio: string;
    displayName: string;
    role: UserRole;
}
export type RatingId = bigint;
export interface RatingView {
    id: RatingId;
    clientId: UserId;
    bookingId: BookingId;
    createdAt: Timestamp;
    comment?: string;
    stars: bigint;
    providerReply?: string;
    serviceId: ServiceId;
    providerId: UserId;
}
export type ServiceId = bigint;
export type BookingId = bigint;
export interface InvoiceView {
    id: InvoiceId;
    clientId: UserId;
    bookingId: BookingId;
    createdAt: Timestamp;
    serviceId: ServiceId;
    amount: bigint;
    providerId: UserId;
}
export interface BookingView {
    id: BookingId;
    clientId: UserId;
    createdAt: Timestamp;
    quoteId: QuoteId;
    agreedPrice: bigint;
    escrowStatus: EscrowStatus;
    updatedAt: Timestamp;
    bookingStatus: BookingStatus;
    serviceId: ServiceId;
    providerId: UserId;
}
export interface CreateServiceInput {
    title: string;
    description: string;
    category: ServiceCategory;
    priceType: PriceType;
    basePrice: bigint;
}
export interface CreateRatingInput {
    bookingId: BookingId;
    comment?: string;
    stars: bigint;
}
export type UserId = Principal;
export interface ReplyQuoteInput {
    estimationBreakdown?: EstimationBreakdown;
    replyMessage?: string;
    proposedPrice?: bigint;
    replyType: ReplyType;
    proposedTimeline?: string;
}
export type NotificationId = bigint;
export type InvoiceId = bigint;
export interface ServiceView {
    id: ServiceId;
    title: string;
    createdAt: Timestamp;
    description: string;
    category: ServiceCategory;
    priceType: PriceType;
    basePrice: bigint;
    providerId: UserId;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    displayName: string;
    createdAt: Timestamp;
    role: UserRole;
}
export interface QuoteView {
    id: QuoteId;
    status: QuoteStatus;
    clientId: UserId;
    createdAt: Timestamp;
    estimationBreakdown?: EstimationBreakdown;
    updatedAt: Timestamp;
    replyMessage?: string;
    proposedPrice?: bigint;
    serviceId: ServiceId;
    replyType?: ReplyType;
    requirements: string;
    providerId: UserId;
    attachments: Array<string>;
    proposedTimeline?: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    disputed = "disputed",
    started = "started",
    completed = "completed",
    paymentPending = "paymentPending"
}
export enum EscrowStatus {
    held = "held",
    none = "none",
    refunded = "refunded",
    released = "released"
}
export enum NotificationType {
    bookingConfirmed = "bookingConfirmed",
    paymentReceived = "paymentReceived",
    quoteReceived = "quoteReceived",
    replyReceived = "replyReceived"
}
export enum PriceType {
    fixed = "fixed",
    onSiteEstimate = "onSiteEstimate"
}
export enum QuoteStatus {
    cancelled = "cancelled",
    pending = "pending",
    replied = "replied",
    rejected = "rejected",
    accepted = "accepted"
}
export enum ReplyType {
    detailedEstimate = "detailedEstimate",
    onSiteEstimate = "onSiteEstimate",
    messageOnly = "messageOnly"
}
export enum ServiceCategory {
    it = "it",
    cleaning = "cleaning",
    other = "other",
    marketing = "marketing",
    garden = "garden",
    design = "design",
    homeRepair = "homeRepair"
}
export enum UserRole {
    client = "client",
    provider = "provider"
}
export interface backendInterface {
    acceptQuote(quoteId: QuoteId): Promise<QuoteView | null>;
    cancelBooking(bookingId: BookingId): Promise<BookingView | null>;
    cancelQuote(quoteId: QuoteId): Promise<QuoteView | null>;
    createBooking(quoteId: QuoteId): Promise<BookingView>;
    createRating(input: CreateRatingInput): Promise<RatingView>;
    createService(input: CreateServiceInput): Promise<ServiceView>;
    deleteService(serviceId: ServiceId): Promise<boolean>;
    getBooking(bookingId: BookingId): Promise<BookingView | null>;
    getInvoice(invoiceId: InvoiceId): Promise<InvoiceView | null>;
    getInvoiceByBooking(bookingId: BookingId): Promise<InvoiceView | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getQuote(quoteId: QuoteId): Promise<QuoteView | null>;
    getService(serviceId: ServiceId): Promise<ServiceView | null>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    listMyClientBookings(): Promise<Array<BookingView>>;
    listMyClientInvoices(): Promise<Array<InvoiceView>>;
    listMyClientQuotes(): Promise<Array<QuoteView>>;
    listMyProviderBookings(): Promise<Array<BookingView>>;
    listMyProviderInvoices(): Promise<Array<InvoiceView>>;
    listMyProviderQuotes(): Promise<Array<QuoteView>>;
    listMyServices(): Promise<Array<ServiceView>>;
    listNotifications(offset: bigint, limit: bigint): Promise<Array<NotificationView>>;
    listProviderRatings(providerId: UserId): Promise<Array<RatingView>>;
    listServiceRatings(serviceId: ServiceId): Promise<Array<RatingView>>;
    listServices(category: ServiceCategory | null): Promise<Array<ServiceView>>;
    markAllNotificationsAsRead(): Promise<void>;
    markBookingCompleted(bookingId: BookingId): Promise<BookingView | null>;
    markBookingDisputed(bookingId: BookingId): Promise<BookingView | null>;
    markBookingStarted(bookingId: BookingId): Promise<BookingView | null>;
    markNotificationAsRead(notificationId: NotificationId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(input: RegisterInput): Promise<UserProfile>;
    rejectQuote(quoteId: QuoteId): Promise<QuoteView | null>;
    releaseEscrow(bookingId: BookingId): Promise<BookingView | null>;
    replyQuote(quoteId: QuoteId, input: ReplyQuoteInput): Promise<QuoteView | null>;
    replyRating(ratingId: RatingId, reply: string): Promise<RatingView | null>;
    requestQuote(input: RequestQuoteInput): Promise<QuoteView>;
    updateService(serviceId: ServiceId, input: UpdateServiceInput): Promise<ServiceView | null>;
}
import type { BookingId as _BookingId, BookingStatus as _BookingStatus, BookingView as _BookingView, CreateRatingInput as _CreateRatingInput, CreateServiceInput as _CreateServiceInput, EscrowStatus as _EscrowStatus, EstimationBreakdown as _EstimationBreakdown, InvoiceView as _InvoiceView, NotificationId as _NotificationId, NotificationType as _NotificationType, NotificationView as _NotificationView, PriceType as _PriceType, QuoteId as _QuoteId, QuoteStatus as _QuoteStatus, QuoteView as _QuoteView, RatingId as _RatingId, RatingView as _RatingView, RegisterInput as _RegisterInput, ReplyQuoteInput as _ReplyQuoteInput, ReplyType as _ReplyType, ServiceCategory as _ServiceCategory, ServiceId as _ServiceId, ServiceView as _ServiceView, Timestamp as _Timestamp, UpdateServiceInput as _UpdateServiceInput, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptQuote(arg0: QuoteId): Promise<QuoteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptQuote(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptQuote(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelQuote(arg0: QuoteId): Promise<QuoteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelQuote(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelQuote(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: QuoteId): Promise<BookingView> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_BookingView_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_BookingView_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRating(arg0: CreateRatingInput): Promise<RatingView> {
        if (this.processError) {
            try {
                const result = await this.actor.createRating(to_candid_CreateRatingInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RatingView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRating(to_candid_CreateRatingInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RatingView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: CreateServiceInput): Promise<ServiceView> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_CreateServiceInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ServiceView_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_CreateServiceInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ServiceView_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteService(arg0: ServiceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getBooking(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<InvoiceView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceByBooking(arg0: BookingId): Promise<InvoiceView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceByBooking(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceByBooking(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuote(arg0: QuoteId): Promise<QuoteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuote(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuote(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<ServiceView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyClientBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyClientBookings();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyClientBookings();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyClientInvoices(): Promise<Array<InvoiceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyClientInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyClientInvoices();
            return result;
        }
    }
    async listMyClientQuotes(): Promise<Array<QuoteView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyClientQuotes();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyClientQuotes();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyProviderBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProviderBookings();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProviderBookings();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyProviderInvoices(): Promise<Array<InvoiceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProviderInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProviderInvoices();
            return result;
        }
    }
    async listMyProviderQuotes(): Promise<Array<QuoteView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProviderQuotes();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProviderQuotes();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyServices(): Promise<Array<ServiceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyServices();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyServices();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotifications(arg0: bigint, arg1: bigint): Promise<Array<NotificationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications(arg0, arg1);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications(arg0, arg1);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProviderRatings(arg0: UserId): Promise<Array<RatingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProviderRatings(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProviderRatings(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServiceRatings(arg0: ServiceId): Promise<Array<RatingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServiceRatings(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServiceRatings(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(arg0: ServiceCategory | null): Promise<Array<ServiceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsAsRead();
            return result;
        }
    }
    async markBookingCompleted(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingCompleted(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingCompleted(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markBookingDisputed(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingDisputed(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingDisputed(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markBookingStarted(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingStarted(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingStarted(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationAsRead(arg0: NotificationId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterInput_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterInput_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectQuote(arg0: QuoteId): Promise<QuoteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectQuote(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectQuote(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async releaseEscrow(arg0: BookingId): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseEscrow(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseEscrow(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyQuote(arg0: QuoteId, arg1: ReplyQuoteInput): Promise<QuoteView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.replyQuote(arg0, to_candid_ReplyQuoteInput_n57(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyQuote(arg0, to_candid_ReplyQuoteInput_n57(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyRating(arg0: RatingId, arg1: string): Promise<RatingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.replyRating(arg0, arg1);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyRating(arg0, arg1);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestQuote(arg0: RequestQuoteInput): Promise<QuoteView> {
        if (this.processError) {
            try {
                const result = await this.actor.requestQuote(arg0);
                return from_candid_QuoteView_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestQuote(arg0);
            return from_candid_QuoteView_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateService(arg0: ServiceId, arg1: UpdateServiceInput): Promise<ServiceView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, to_candid_UpdateServiceInput_n62(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, to_candid_UpdateServiceInput_n62(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BookingView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingView): BookingView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EscrowStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscrowStatus): EscrowStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationView): NotificationView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PriceType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceType): PriceType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteStatus): QuoteStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_QuoteView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteView): QuoteView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RatingView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RatingView): RatingView {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ReplyType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReplyType): ReplyType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceView): ServiceView {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuoteView]): QuoteView | null {
    return value.length === 0 ? null : from_candid_QuoteView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingView]): BookingView | null {
    return value.length === 0 ? null : from_candid_BookingView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceView]): InvoiceView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceView]): ServiceView | null {
    return value.length === 0 ? null : from_candid_ServiceView_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EstimationBreakdown]): EstimationBreakdown | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RatingView]): RatingView | null {
    return value.length === 0 ? null : from_candid_RatingView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReplyType]): ReplyType | null {
    return value.length === 0 ? null : from_candid_ReplyType_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    clientId: _UserId;
    createdAt: _Timestamp;
    quoteId: _QuoteId;
    agreedPrice: bigint;
    escrowStatus: _EscrowStatus;
    updatedAt: _Timestamp;
    bookingStatus: _BookingStatus;
    serviceId: _ServiceId;
    providerId: _UserId;
}): {
    id: BookingId;
    clientId: UserId;
    createdAt: Timestamp;
    quoteId: QuoteId;
    agreedPrice: bigint;
    escrowStatus: EscrowStatus;
    updatedAt: Timestamp;
    bookingStatus: BookingStatus;
    serviceId: ServiceId;
    providerId: UserId;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        createdAt: value.createdAt,
        quoteId: value.quoteId,
        agreedPrice: value.agreedPrice,
        escrowStatus: from_candid_EscrowStatus_n15(_uploadFile, _downloadFile, value.escrowStatus),
        updatedAt: value.updatedAt,
        bookingStatus: from_candid_BookingStatus_n17(_uploadFile, _downloadFile, value.bookingStatus),
        serviceId: value.serviceId,
        providerId: value.providerId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RatingId;
    clientId: _UserId;
    bookingId: _BookingId;
    createdAt: _Timestamp;
    comment: [] | [string];
    stars: bigint;
    providerReply: [] | [string];
    serviceId: _ServiceId;
    providerId: _UserId;
}): {
    id: RatingId;
    clientId: UserId;
    bookingId: BookingId;
    createdAt: Timestamp;
    comment?: string;
    stars: bigint;
    providerReply?: string;
    serviceId: ServiceId;
    providerId: UserId;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        comment: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.comment)),
        stars: value.stars,
        providerReply: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.providerReply)),
        serviceId: value.serviceId,
        providerId: value.providerId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuoteId;
    status: _QuoteStatus;
    clientId: _UserId;
    createdAt: _Timestamp;
    estimationBreakdown: [] | [_EstimationBreakdown];
    updatedAt: _Timestamp;
    replyMessage: [] | [string];
    proposedPrice: [] | [bigint];
    serviceId: _ServiceId;
    replyType: [] | [_ReplyType];
    requirements: string;
    providerId: _UserId;
    attachments: Array<string>;
    proposedTimeline: [] | [string];
}): {
    id: QuoteId;
    status: QuoteStatus;
    clientId: UserId;
    createdAt: Timestamp;
    estimationBreakdown?: EstimationBreakdown;
    updatedAt: Timestamp;
    replyMessage?: string;
    proposedPrice?: bigint;
    serviceId: ServiceId;
    replyType?: ReplyType;
    requirements: string;
    providerId: UserId;
    attachments: Array<string>;
    proposedTimeline?: string;
} {
    return {
        id: value.id,
        status: from_candid_QuoteStatus_n4(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        createdAt: value.createdAt,
        estimationBreakdown: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.estimationBreakdown)),
        updatedAt: value.updatedAt,
        replyMessage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyMessage)),
        proposedPrice: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.proposedPrice)),
        serviceId: value.serviceId,
        replyType: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.replyType)),
        requirements: value.requirements,
        providerId: value.providerId,
        attachments: value.attachments,
        proposedTimeline: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.proposedTimeline))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ServiceId;
    title: string;
    createdAt: _Timestamp;
    description: string;
    category: _ServiceCategory;
    priceType: _PriceType;
    basePrice: bigint;
    providerId: _UserId;
}): {
    id: ServiceId;
    title: string;
    createdAt: Timestamp;
    description: string;
    category: ServiceCategory;
    priceType: PriceType;
    basePrice: bigint;
    providerId: UserId;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        category: from_candid_ServiceCategory_n31(_uploadFile, _downloadFile, value.category),
        priceType: from_candid_PriceType_n33(_uploadFile, _downloadFile, value.priceType),
        basePrice: value.basePrice,
        providerId: value.providerId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    displayName: string;
    createdAt: _Timestamp;
    role: _UserRole;
}): {
    id: UserId;
    bio: string;
    displayName: string;
    createdAt: Timestamp;
    role: UserRole;
} {
    return {
        id: value.id,
        bio: value.bio,
        displayName: value.displayName,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n39(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    notifType: _NotificationType;
    body: string;
    link: string;
    createdAt: _Timestamp;
    isRead: boolean;
    recipientId: _UserId;
}): {
    id: NotificationId;
    title: string;
    notifType: NotificationType;
    body: string;
    link: string;
    createdAt: Timestamp;
    isRead: boolean;
    recipientId: UserId;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotificationType_n48(_uploadFile, _downloadFile, value.notifType),
        body: value.body,
        link: value.link,
        createdAt: value.createdAt,
        isRead: value.isRead,
        recipientId: value.recipientId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    detailedEstimate: null;
} | {
    onSiteEstimate: null;
} | {
    messageOnly: null;
}): ReplyType {
    return "detailedEstimate" in value ? ReplyType.detailedEstimate : "onSiteEstimate" in value ? ReplyType.onSiteEstimate : "messageOnly" in value ? ReplyType.messageOnly : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    held: null;
} | {
    none: null;
} | {
    refunded: null;
} | {
    released: null;
}): EscrowStatus {
    return "held" in value ? EscrowStatus.held : "none" in value ? EscrowStatus.none : "refunded" in value ? EscrowStatus.refunded : "released" in value ? EscrowStatus.released : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    disputed: null;
} | {
    started: null;
} | {
    completed: null;
} | {
    paymentPending: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "disputed" in value ? BookingStatus.disputed : "started" in value ? BookingStatus.started : "completed" in value ? BookingStatus.completed : "paymentPending" in value ? BookingStatus.paymentPending : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    it: null;
} | {
    cleaning: null;
} | {
    other: null;
} | {
    marketing: null;
} | {
    garden: null;
} | {
    design: null;
} | {
    homeRepair: null;
}): ServiceCategory {
    return "it" in value ? ServiceCategory.it : "cleaning" in value ? ServiceCategory.cleaning : "other" in value ? ServiceCategory.other : "marketing" in value ? ServiceCategory.marketing : "garden" in value ? ServiceCategory.garden : "design" in value ? ServiceCategory.design : "homeRepair" in value ? ServiceCategory.homeRepair : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    onSiteEstimate: null;
}): PriceType {
    return "fixed" in value ? PriceType.fixed : "onSiteEstimate" in value ? PriceType.onSiteEstimate : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    provider: null;
}): UserRole {
    return "client" in value ? UserRole.client : "provider" in value ? UserRole.provider : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingConfirmed: null;
} | {
    paymentReceived: null;
} | {
    quoteReceived: null;
} | {
    replyReceived: null;
}): NotificationType {
    return "bookingConfirmed" in value ? NotificationType.bookingConfirmed : "paymentReceived" in value ? NotificationType.paymentReceived : "quoteReceived" in value ? NotificationType.quoteReceived : "replyReceived" in value ? NotificationType.replyReceived : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    replied: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): QuoteStatus {
    return "cancelled" in value ? QuoteStatus.cancelled : "pending" in value ? QuoteStatus.pending : "replied" in value ? QuoteStatus.replied : "rejected" in value ? QuoteStatus.rejected : "accepted" in value ? QuoteStatus.accepted : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingView>): Array<BookingView> {
    return value.map((x)=>from_candid_BookingView_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuoteView>): Array<QuoteView> {
    return value.map((x)=>from_candid_QuoteView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceView>): Array<ServiceView> {
    return value.map((x)=>from_candid_ServiceView_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationView>): Array<NotificationView> {
    return value.map((x)=>from_candid_NotificationView_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RatingView>): Array<RatingView> {
    return value.map((x)=>from_candid_RatingView_n21(_uploadFile, _downloadFile, x));
}
function to_candid_CreateRatingInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRatingInput): _CreateRatingInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CreateServiceInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateServiceInput): _CreateServiceInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PriceType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceType): _PriceType {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterInput_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterInput): _RegisterInput {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_ReplyQuoteInput_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReplyQuoteInput): _ReplyQuoteInput {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_ReplyType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReplyType): _ReplyType {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateServiceInput_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateServiceInput): _UpdateServiceInput {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory | null): [] | [_ServiceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ServiceCategory_n25(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingId: BookingId;
    comment?: string;
    stars: bigint;
}): {
    bookingId: _BookingId;
    comment: [] | [string];
    stars: bigint;
} {
    return {
        bookingId: value.bookingId,
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        stars: value.stars
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    category: ServiceCategory;
    priceType: PriceType;
    basePrice: bigint;
}): {
    title: string;
    description: string;
    category: _ServiceCategory;
    priceType: _PriceType;
    basePrice: bigint;
} {
    return {
        title: value.title,
        description: value.description,
        category: to_candid_ServiceCategory_n25(_uploadFile, _downloadFile, value.category),
        priceType: to_candid_PriceType_n27(_uploadFile, _downloadFile, value.priceType),
        basePrice: value.basePrice
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    role: UserRole;
}): {
    bio: string;
    displayName: string;
    role: _UserRole;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        role: to_candid_UserRole_n55(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimationBreakdown?: EstimationBreakdown;
    replyMessage?: string;
    proposedPrice?: bigint;
    replyType: ReplyType;
    proposedTimeline?: string;
}): {
    estimationBreakdown: [] | [_EstimationBreakdown];
    replyMessage: [] | [string];
    proposedPrice: [] | [bigint];
    replyType: _ReplyType;
    proposedTimeline: [] | [string];
} {
    return {
        estimationBreakdown: value.estimationBreakdown ? candid_some(value.estimationBreakdown) : candid_none(),
        replyMessage: value.replyMessage ? candid_some(value.replyMessage) : candid_none(),
        proposedPrice: value.proposedPrice ? candid_some(value.proposedPrice) : candid_none(),
        replyType: to_candid_ReplyType_n59(_uploadFile, _downloadFile, value.replyType),
        proposedTimeline: value.proposedTimeline ? candid_some(value.proposedTimeline) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    description?: string;
    category?: ServiceCategory;
    priceType?: PriceType;
    basePrice?: bigint;
}): {
    title: [] | [string];
    description: [] | [string];
    category: [] | [_ServiceCategory];
    priceType: [] | [_PriceType];
    basePrice: [] | [bigint];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        category: value.category ? candid_some(to_candid_ServiceCategory_n25(_uploadFile, _downloadFile, value.category)) : candid_none(),
        priceType: value.priceType ? candid_some(to_candid_PriceType_n27(_uploadFile, _downloadFile, value.priceType)) : candid_none(),
        basePrice: value.basePrice ? candid_some(value.basePrice) : candid_none()
    };
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    it: null;
} | {
    cleaning: null;
} | {
    other: null;
} | {
    marketing: null;
} | {
    garden: null;
} | {
    design: null;
} | {
    homeRepair: null;
} {
    return value == ServiceCategory.it ? {
        it: null
    } : value == ServiceCategory.cleaning ? {
        cleaning: null
    } : value == ServiceCategory.other ? {
        other: null
    } : value == ServiceCategory.marketing ? {
        marketing: null
    } : value == ServiceCategory.garden ? {
        garden: null
    } : value == ServiceCategory.design ? {
        design: null
    } : value == ServiceCategory.homeRepair ? {
        homeRepair: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceType): {
    fixed: null;
} | {
    onSiteEstimate: null;
} {
    return value == PriceType.fixed ? {
        fixed: null
    } : value == PriceType.onSiteEstimate ? {
        onSiteEstimate: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    client: null;
} | {
    provider: null;
} {
    return value == UserRole.client ? {
        client: null
    } : value == UserRole.provider ? {
        provider: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReplyType): {
    detailedEstimate: null;
} | {
    onSiteEstimate: null;
} | {
    messageOnly: null;
} {
    return value == ReplyType.detailedEstimate ? {
        detailedEstimate: null
    } : value == ReplyType.onSiteEstimate ? {
        onSiteEstimate: null
    } : value == ReplyType.messageOnly ? {
        messageOnly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
